# fly.toml for API service
app = "hellishot-api-taylor"
primary_region = "iad"

[build]
# Uses Dockerfile by default

[env]
PORT = "8080"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 50
soft_limit = 25
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = "10s"
grace_period = "10s"
method = "get"
path = "/api/health"
protocol = "http"
timeout = "2s"

[checks]
[checks.health]
type = "http"
port = 8080
interval = "10s"
timeout = "2s"
method = "get"
path = "/api/health"
