# fly.toml for Web (static + proxy to API)
app = "hellishot-web-taylor"
primary_region = "iad"

[build]
# Uses Dockerfile by default

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 50
soft_limit = 25
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
